### ISSUE TITLE
puppet_bridge error when starting docker container

### ISSUE THREAD

**Issue by jschlatow** [Sorunome/mx-puppet-slack#124]
Hi, I'm getting the following error when starting the docker container. I've added the config.yaml, generated the slack-registration.yaml, registered the app service at my homeserver and restarted the latter.

> Jun-12 09:58:26.591 [PuppetBridge] error: Unhandled Promise Rejection: TypeError: Cannot read property 'endsWith' of undefined
    at new MatrixClient (/opt/mx-puppet-slack/node_modules/@sorunome/matrix-bot-sdk/lib/MatrixClient.js:79:32)
    at new Intent (/opt/mx-puppet-slack/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Intent.js:44:23)
    at Appservice.getIntentForUserId (/opt/mx-puppet-slack/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:231:22)
    at Appservice.get botIntent [as botIntent] (/opt/mx-puppet-slack/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:132:21)
    at Appservice.<anonymous> (/opt/mx-puppet-slack/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:154:32)
    at Generator.next (<anonymous>)
    at /opt/mx-puppet-slack/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/mx-puppet-slack/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:4:12)
    at registerBotIntent (/opt/mx-puppet-slack/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:152:45)

**Comment by jukefr** [comment]
had the same issue was an indentation problem in my `config.yml` if that helps anybody
