### ISSUE TITLE
Emoji reactions are not being bridged matrix > Slack

### ISSUE THREAD

**Issue by ericmigi** [Sorunome/mx-puppet-slack#41]
Other way works though.

**Comment by Sorunome** [comment]
fixed in https://github.com/Sorunome/mx-puppet-slack/commit/4b452b8077ad2b9616fc78d544fb9588f0dda02f

**Comment by ericmigi** [comment]
Hmm it works in one rooms (with slackbot) but not in any other rooms. throws this error

```
mx-puppet-slack              | Apr-7 01:56:48.819 [bot-sdk-Appservice] info: Processing transaction 19403
mx-puppet-slack              | Apr-7 01:56:48.820 [bot-sdk-Appservice] info: Processing event of type m.reaction
mx-puppet-slack              | Apr-7 01:56:48.824 [MatrixEventHandler] info: Got new message in !qYnpLgvFnRtDxVYXrQ:eric.nova.chat from @eric:eric.nova.chat!
mx-puppet-slack              | Apr-7 01:56:48.825 [MatrixEventHandler] info: Handling text event with msgtype m.reaction...
mx-puppet-slack              | 172.18.0.3 - - [07/Apr/2020:01:56:48 +0000] "PUT /transactions/19403?access_token= HTTP/1.1" 200 2 "-" "Synapse/1.9.1"
mx-puppet-slack              | (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
mx-puppet-slack              |     at MatrixMessageParser.<anonymous> (/opt/mx-puppet-slack/node_modules/matrix-slack-parser/lib/src/matrixmessageparser.js:66:43)
mx-puppet-slack              |     at Generator.next (<anonymous>)
mx-puppet-slack              |     at /opt/mx-puppet-slack/node_modules/matrix-slack-parser/lib/src/matrixmessageparser.js:21:71
mx-puppet-slack              |     at new Promise (<anonymous>)
mx-puppet-slack              |     at __awaiter (/opt/mx-puppet-slack/node_modules/matrix-slack-parser/lib/src/matrixmessageparser.js:17:12)
mx-puppet-slack              |     at MatrixMessageParser.escapeSlack (/opt/mx-puppet-slack/node_modules/matrix-slack-parser/lib/src/matrixmessageparser.js:64:16)
mx-puppet-slack              |     at MatrixMessageParser.<anonymous> (/opt/mx-puppet-slack/node_modules/matrix-slack-parser/lib/src/matrixmessageparser.js:53:37)
mx-puppet-slack              |     at Generator.next (<anonymous>)
mx-puppet-slack              |     at /opt/mx-puppet-slack/node_modules/matrix-slack-parser/lib/src/matrixmessageparser.js:21:71
mx-puppet-slack              |     at new Promise (<anonymous>)
mx-puppet-slack              |     at __awaiter (/opt/mx-puppet-slack/node_modules/matrix-slack-parser/lib/src/matrixmessageparser.js:17:12)
mx-puppet-slack              |     at MatrixMessageParser.FormatMessage (/opt/mx-puppet-slack/node_modules/matrix-slack-parser/lib/src/matrixmessageparser.js:33:16)
mx-puppet-slack              |     at App.<anonymous> (/opt/mx-puppet-slack/build/slack.js:471:56)
mx-puppet-slack              |     at Generator.next (<anonymous>)
mx-puppet-slack              |     at /opt/mx-puppet-slack/build/slack.js:8:71
mx-puppet-slack              |     at new Promise (<anonymous>)
mx-puppet-slack              |     at __awaiter (/opt/mx-puppet-slack/build/slack.js:4:12)
mx-puppet-slack              |     at App.handleMatrixMessage (/opt/mx-puppet-slack/build/slack.js:461:16)
mx-puppet-slack              |     at PuppetBridge.emit (events.js:315:20)
mx-puppet-slack              |     at MatrixEventHandler.<anonymous> (/opt/mx-puppet-slack/node_modules/mx-puppet-bridge/lib/src/matrixeventhandler.js:409:25)mx-puppet-slack              |     at Generator.next (<anonymous>)
mx-puppet-slack              |     at fulfilled (/opt/mx-puppet-slack/node_modules/mx-puppet-bridge/lib/src/matrixeventhandler.js:17:58)
mx-puppet-slack              | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

```

**Comment by ericmigi** [comment]
this is a bit of a weird one, any more logs I could pull to help, @Sorunome?

**Comment by Sorunome** [comment]
Can you enable in riot "Show hidden events in timeline", that is under labs?

After that, go to the reaction even which is causing the issues and paste its content here?

**Comment by ericmigi** [comment]
![image](https://user-images.githubusercontent.com/1048265/78821225-fd956f00-798d-11ea-9968-61cf0a84dfec.png)

**Comment by Sorunome** [comment]
yes, and the contents? Either click the arrow thingies on the right or click "view source"

**Comment by ericmigi** [comment]
```
{
    "type": "m.reaction",
    "sender": "@eric:eric.nova.chat",
    "content": {
        "m.relates_to": {
            "rel_type": "m.annotation",
            "event_id": "$kMm9NjFsUgBaxEi41bZpnteC1O3dwQsjlGZ5z_VwRNk",
            "key": "👍️"
        }
    },
    "event_id": "$cwbwbmcdTj3pl0u-n6ZZGki5-KNQe6ggd_AyxZYMZzo",
    "origin_server_ts": 1586371323383,
    "unsigned": {
        "age": 116,
        "transaction_id": "m1586371323226.43"
    },
    "room_id": "!LFwfUKtkhJBUzfGHdL:eric.nova.chat"
}

```

**Comment by Sorunome** [comment]
fixed in https://github.com/Sorunome/mx-puppet-bridge/commit/c9750f8afadf47d7d02582e776ae46162dfade93

**Comment by ericmigi** [comment]
That fixed it, thanks!
