### ISSUE TITLE
Messages from users of other teams missing in shared channels

### ISSUE THREAD

**Issue by twouters** [Sorunome/mx-puppet-slack#46]
Message events from external users in [shared channels](https://slack.com/resources/using-slack/setting-up-a-shared-channel) throw the following exception/warning and don't end up in Matrix.

```
Apr 01 10:39:20 midgard node[57488]: (node:57488) UnhandledPromiseRejectionWarning: Error: User or channel not found
Apr 01 10:39:20 midgard node[57488]:     at new Message (/home/twouters/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/message.js:37:19)
Apr 01 10:39:20 midgard node[57488]:     at Client.<anonymous> (/home/twouters/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:714:33)
Apr 01 10:39:20 midgard node[57488]:     at Generator.next (<anonymous>)
Apr 01 10:39:20 midgard node[57488]:     at /home/twouters/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:20:71
Apr 01 10:39:20 midgard node[57488]:     at new Promise (<anonymous>)
Apr 01 10:39:20 midgard node[57488]:     at __awaiter (/home/twouters/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:16:12)
Apr 01 10:39:20 midgard node[57488]:     at Client.handleMessageEvent (/home/twouters/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:679:16)
Apr 01 10:39:20 midgard node[57488]:     at Client.<anonymous> (/home/twouters/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:300:36)
Apr 01 10:39:20 midgard node[57488]:     at Generator.next (<anonymous>)
Apr 01 10:39:20 midgard node[57488]:     at /home/twouters/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:20:71
Apr 01 10:39:20 midgard node[57488]:     at new Promise (<anonymous>)
Apr 01 10:39:20 midgard node[57488]:     at __awaiter (/home/twouters/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:16:12)
Apr 01 10:39:20 midgard node[57488]:     at RTMClient.<anonymous> (/home/twouters/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:297:49)
Apr 01 10:39:20 midgard node[57488]:     at RTMClient.emit (/home/twouters/mx-puppet-slack/node_modules/eventemitter3/index.js:181:35)
Apr 01 10:39:20 midgard node[57488]:     at RTMClient.onWebsocketMessage (/home/twouters/mx-puppet-slack/node_modules/@slack/rtm-api/dist/RTMClient.js:457:14)
Apr 01 10:39:20 midgard node[57488]:     at WebSocket.onMessage (/home/twouters/mx-puppet-slack/node_modules/ws/lib/event-target.js:120:16)
Apr 01 10:39:20 midgard node[57488]:     at WebSocket.emit (events.js:315:20)
Apr 01 10:39:20 midgard node[57488]:     at Receiver.receiverOnMessage (/home/twouters/mx-puppet-slack/node_modules/ws/lib/websocket.js:720:20)
Apr 01 10:39:20 midgard node[57488]:     at Receiver.emit (events.js:315:20)
Apr 01 10:39:20 midgard node[57488]:     at Receiver.dataMessage (/home/twouters/mx-puppet-slack/node_modules/ws/lib/receiver.js:414:14)
Apr 01 10:39:20 midgard node[57488]:     at Receiver.getData (/home/twouters/mx-puppet-slack/node_modules/ws/lib/receiver.js:346:17)
Apr 01 10:39:20 midgard node[57488]:     at Receiver.startLoop (/home/twouters/mx-puppet-slack/node_modules/ws/lib/receiver.js:133:22)
Apr 01 10:39:20 midgard node[57488]: (node:57488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 945)
```

**Comment by Sorunome** [comment]
This will be a bigger one to fix 🤔  Do you have how the message object looks like? (log level `silly`)

**Comment by twouters** [comment]
Used to work in the old implementation, so working example should be in git somewhere :)

```
Apr 01 10:39:20 midgard node[57488]: Apr-1 10:39:20.814 [SlackClient:Client] silly: Processing message with data {
Apr 01 10:39:20 midgard node[57488]:   client_msg_id: '5db2b542-c5fc-45b6-b7d1-xxxxxxxxxxx',
Apr 01 10:39:20 midgard node[57488]:   suppress_notification: false,
Apr 01 10:39:20 midgard node[57488]:   type: 'message',
Apr 01 10:39:20 midgard node[57488]:   text: 'message content',
Apr 01 10:39:20 midgard node[57488]:   user: 'U15XXXXXX',
Apr 01 10:39:20 midgard node[57488]:   team: 'T0BXXXXXX',
Apr 01 10:39:20 midgard node[57488]:   blocks: [ { type: 'rich_text', block_id: 'Njj', elements: [Array] } ],
Apr 01 10:39:20 midgard node[57488]:   thread_ts: '1585730205.002500',
Apr 01 10:39:20 midgard node[57488]:   source_team: 'T0BXXXXXX',
Apr 01 10:39:20 midgard node[57488]:   user_team: 'T0BXXXXXX',
Apr 01 10:39:20 midgard node[57488]:   channel: 'C9BXXXXXX',
Apr 01 10:39:20 midgard node[57488]:   event_ts: '1585730360.003400',
Apr 01 10:39:20 midgard node[57488]:   ts: '1585730360.003400',
Apr 01 10:39:20 midgard node[57488]:   team_id: 'T04XXXXXX'
Apr 01 10:39:20 midgard node[57488]: }
```

**Comment by Sorunome** [comment]
Fixed by now, yay
