### ISSUE TITLE
Unhandled event 'explicit disconnect' in state 'disconnected'.

### ISSUE THREAD

**Issue by inducer** [Sorunome/mx-puppet-slack#47]
I've been running `mx-puppet-slack` on my homeserver with good success, however every now and then the bridge simply falls over and dies. This is one log entry that I was able to recover that could help shed some light:

```
Apr 01 01:08:06 marten npm[1110082]: /var/lib/mx-puppet-slack/mx-puppet-slack/node_modules/finity/lib/core/StateMachine.js:76
Apr 01 01:08:06 marten npm[1110082]:       throw new Error('Unhandled event \'' + event + '\' in state \'' + this.currentState + '\'.');
Apr 01 01:08:06 marten npm[1110082]:       ^
Apr 01 01:08:06 marten npm[1110082]: Error: Unhandled event 'explicit disconnect' in state 'disconnected'.
Apr 01 01:08:06 marten npm[1110082]:     at StateMachine.handleUnhandledEvent (/var/lib/mx-puppet-slack/mx-puppet-slack/node_modules/finity/lib/core/StateMachine.js:76:13)
Apr 01 01:08:06 marten npm[1110082]:     at /var/lib/mx-puppet-slack/mx-puppet-slack/node_modules/finity/lib/core/HierarchicalStateMachine.js:79:33
Apr 01 01:08:06 marten npm[1110082]:     at TaskScheduler.execute (/var/lib/mx-puppet-slack/mx-puppet-slack/node_modules/finity/lib/core/TaskScheduler.js:32:9)
Apr 01 01:08:06 marten npm[1110082]:     at TaskScheduler.enqueue (/var/lib/mx-puppet-slack/mx-puppet-slack/node_modules/finity/lib/core/TaskScheduler.js:19:12)
Apr 01 01:08:06 marten npm[1110082]:     at HierarchicalStateMachine.handle (/var/lib/mx-puppet-slack/mx-puppet-slack/node_modules/finity/lib/core/HierarchicalStateMachine.js:72:24)
Apr 01 01:08:06 marten npm[1110082]:     at WebSocket.<anonymous> (/var/lib/mx-puppet-slack/mx-puppet-slack/node_modules/soru-slack-client/node_modules/@slack/rtm-api/dist/RTMClient.js:405:77)
Apr 01 01:08:06 marten npm[1110082]:     at WebSocket.onClose (/var/lib/mx-puppet-slack/mx-puppet-slack/node_modules/ws/lib/event-target.js:124:16)
Apr 01 01:08:06 marten npm[1110082]:     at WebSocket.emit (events.js:203:13)
Apr 01 01:08:06 marten npm[1110082]:     at WebSocket.emitClose (/var/lib/mx-puppet-slack/mx-puppet-slack/node_modules/ws/lib/websocket.js:172:10)
Apr 01 01:08:06 marten npm[1110082]:     at TLSSocket.socketOnClose (/var/lib/mx-puppet-slack/mx-puppet-slack/node_modules/ws/lib/websocket.js:781:15)
Apr 01 01:08:06 marten npm[1110082]:     at TLSSocket.emit (events.js:208:15)
Apr 01 01:08:06 marten npm[1110082]:     at net.js:588:12
Apr 01 01:08:06 marten npm[1110082]:     at TCP.done (_tls_wrap.js:479:7)
Apr 01 01:08:06 marten npm[1109982]: npm ERR! code ELIFECYCLE
Apr 01 01:08:06 marten npm[1109982]: npm ERR! errno 1
Apr 01 01:08:06 marten npm[1109982]: npm ERR! mx-puppet-slack@0.0.0 start: `npm run-script build && node ./build/index.js`
Apr 01 01:08:06 marten npm[1109982]: npm ERR! Exit status 1
Apr 01 01:08:06 marten npm[1109982]: npm ERR!
Apr 01 01:08:06 marten npm[1109982]: npm ERR! Failed at the mx-puppet-slack@0.0.0 start script.
Apr 01 01:08:06 marten npm[1109982]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Apr 01 01:08:06 marten npm[1109982]: npm ERR! A complete log of this run can be found in:
Apr 01 01:08:06 marten npm[1109982]: npm ERR!     /var/lib/mx-puppet-slack/.npm/_logs/2020-03-31T23_08_06_658Z-debug.log
```
For now, I'm working around this by adding
```
[Service]
Restart=always    
RestartSec=5
```
to my systemd unit.

**Comment by Sorunome** [comment]
It's been fixed a few days ago (should be), please try to update :)

Am 1. April 2020 23:45:08 MESZ schrieb "Andreas Klöckner" <notifications@github.com>:

**Comment by inducer** [comment]
Thanks! I've updated and will let you know if it recurs.
