### ISSUE TITLE
Error thrown on `unlink <id>`

### ISSUE THREAD

**Issue by jeffcasavant** [Sorunome/mx-puppet-slack#52]
I can't seem to unlink the teams I've linked so far (I have 3).

```
Apr 10 12:44:13 matrix npm[23550]: Apr-10 12:44:13.888 [bot-sdk-MatrixLiteClient] info: (REQ-162) PUT https://matrix.casavant.org/_matrix/client/r0/presence/%40_slackpuppet___t27_d_l8_q_e5%3D2d_u2_k_d_c_k_q3_s%3Acasavant.org/status
Apr 10 12:44:13 matrix npm[23550]: [ERROR]  WebClient:2 Failed to fetch members for the channel.
Apr 10 12:44:13 matrix npm[23550]: Apr-10 12:44:13.989 [MatrixEventHandler] error: Error handling appservice room.event { Error: An API error occurred: fetch_members_failed
Apr 10 12:44:13 matrix npm[23550]: at Object.platformErrorFromResult (/opt/mx-puppet-slack/node_modules/@slack/web-api/dist/errors.js:50:33)
Apr 10 12:44:13 matrix npm[23550]: at WebClient.apiCall (/opt/mx-puppet-slack/node_modules/@slack/web-api/dist/WebClient.js:485:28)
Apr 10 12:44:13 matrix npm[23550]: at process._tickCallback (internal/process/next_tick.js:68:7)
Apr 10 12:44:13 matrix npm[23550]: code: 'slack_webapi_platform_error',
Apr 10 12:44:13 matrix npm[23550]: data:
Apr 10 12:44:13 matrix npm[23550]: { ok: false,
Apr 10 12:44:13 matrix npm[23550]: error: 'fetch_members_failed',
Apr 10 12:44:13 matrix npm[23550]: response_metadata:
Apr 10 12:44:13 matrix npm[23550]: { messages: [Array], scopes: [Array], acceptedScopes: [Array] } } }
```

**Comment by Sorunome** [comment]
that error seems unrelated to unlink - does it actually unlink the puppet or is it staying linkedfor some reason?

Am 10. April 2020 18:46:49 MESZ schrieb Jeff Casavant <notifications@github.com>:

**Comment by jeffcasavant** [comment]
It stays linked.  When I run unlink this error is always thrown in the logs within a second.

**Comment by Sorunome** [comment]
what kind of token are you using? xoxc? legacy? oauth?

Am 10. April 2020 18:50:07 MESZ schrieb Jeff Casavant <notifications@github.com>:

**Comment by jeffcasavant** [comment]
Legacy.  And there's more log before that, my bad.  Here's the entire thing from a new try:


```
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.752 [bot-sdk-Appservice] info: Processing transaction 10923
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.752 [bot-sdk-Appservice] info: Processing event of type m.room.message
Apr 10 12:50:21 matrix npm[23550]: 127.0.0.1 - - [10/Apr/2020:16:50:21 +0000] "PUT /transactions/10923?access_token=token HTTP/1.1" 200 2 "-" "Synapse/1.12.3"
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.756 [BotProvisioner] info: Got message to process with arg=unlink
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.756 [Provisioner] info: Deleting puppet with id 2
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.759 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.759 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.759 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.759 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.760 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.760 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.760 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.760 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.760 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.762 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.762 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.762 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.763 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.763 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.763 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.763 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.764 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.764 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.764 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.764 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.764 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.764 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.765 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.765 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.765 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.765 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.765 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.765 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.766 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.766 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.766 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.766 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.766 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.766 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.766 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.767 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.767 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.767 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.767 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.769 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.769 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.769 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.769 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.770 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.770 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.770 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.770 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.771 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.772 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.772 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.772 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.773 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.773 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.773 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.773 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.773 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.773 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.773 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.774 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.774 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.774 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.774 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.774 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.774 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=
Apr 10 12:50:21 matrix npm[23550]: [ERROR]  WebClient:2 Failed to fetch members for the channel.
Apr 10 12:50:21 matrix npm[23550]: Apr-10 12:50:21.890 [MatrixEventHandler] error: Error handling appservice room.event { Error: An API error occurred: fetch_members_failed
Apr 10 12:50:21 matrix npm[23550]: at Object.platformErrorFromResult (/opt/mx-puppet-slack/node_modules/@slack/web-api/dist/errors.js:50:33)
Apr 10 12:50:21 matrix npm[23550]: at WebClient.apiCall (/opt/mx-puppet-slack/node_modules/@slack/web-api/dist/WebClient.js:485:28)
Apr 10 12:50:21 matrix npm[23550]: at process._tickCallback (internal/process/next_tick.js:68:7)
Apr 10 12:50:21 matrix npm[23550]: code: 'slack_webapi_platform_error',
Apr 10 12:50:21 matrix npm[23550]: data:
Apr 10 12:50:21 matrix npm[23550]: { ok: false,
Apr 10 12:50:21 matrix npm[23550]: error: 'fetch_members_failed',
Apr 10 12:50:21 matrix npm[23550]: response_metadata:
Apr 10 12:50:21 matrix npm[23550]: { messages: [Array], scopes: [Array], acceptedScopes: [Array] } } }
```

**Comment by Sorunome** [comment]
oooooh soru sees what is going on. soru-slack-client is emitting events that it really shouldn't

Am 10. April 2020 18:52:42 MESZ schrieb Jeff Casavant <notifications@github.com>:

**Comment by Sorunome** [comment]
nevermind, unlink seems to work just fine here o.O

**Comment by Sorunome** [comment]
Is this still the case? Pushed a couple of bugfixes that may or may not be related @jeffcasavant

**Comment by jeffcasavant** [comment]
Pulled & npm updated, same problem.  It's not really a big deal for me, I wouldn't worry about it.  

FYI I did previously have matrix-puppet-slack (and before that matrix-appservice-slack) installed.  Neither are currently running & their registration files are not listed in my homeserver.yaml any more either, but could it be an issue with aliases if their old _rooms_ are still around?


```
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.861 [bot-sdk-Appservice] info: Processing transaction 11038
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.861 [bot-sdk-Appservice] info: Processing event of type m.room.message
May 02 18:16:53 matrix npm[24099]: 127.0.0.1 - - [02/May/2020:22:16:53 +0000] "PUT /transactions/11038?access_token=<TOKEN> HTTP/1.1" 200 2 "-" "Synapse/1.12.4"
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.869 [BotProvisioner] info: Got message to process with arg=unlink
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.869 [Provisioner] info: Deleting puppet with id 1
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.872 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.873 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.873 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.873 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.873 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.873 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.873 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.875 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.875 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.875 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.876 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.876 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.876 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.876 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.876 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.876 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.877 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.877 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.877 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.877 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.877 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.877 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.878 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.878 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.878 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.878 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.878 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.878 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.878 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.878 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.879 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.879 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.879 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.879 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.879 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.879 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.880 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.880 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.880 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.880 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.880 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.880 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.880 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.881 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.881 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.881 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.881 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.882 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.882 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.882 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.883 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.883 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.883 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.883 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.883 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.883 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.884 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.884 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=<room id>
May 02 18:16:53 matrix npm[24099]: [ERROR]  WebClient:4 Failed to fetch members for the channel.
May 02 18:16:53 matrix npm[24099]: May-2 18:16:53.979 [MatrixEventHandler] error: Error handling appservice room.event { Error: An API error occurred: fetch_members_failed
May 02 18:16:53 matrix npm[24099]: at Object.platformErrorFromResult (/opt/mx-puppet-slack/node_modules/@slack/web-api/dist/errors.js:50:33)
May 02 18:16:53 matrix npm[24099]: at WebClient.apiCall (/opt/mx-puppet-slack/node_modules/@slack/web-api/dist/WebClient.js:485:28)
May 02 18:16:53 matrix npm[24099]: at process._tickCallback (internal/process/next_tick.js:68:7)
May 02 18:16:53 matrix npm[24099]: code: 'slack_webapi_platform_error',
May 02 18:16:53 matrix npm[24099]: data:
May 02 18:16:53 matrix npm[24099]: { ok: false,
May 02 18:16:53 matrix npm[24099]: error: 'fetch_members_failed',
May 02 18:16:53 matrix npm[24099]: response_metadata:
May 02 18:16:53 matrix npm[24099]: { messages: [Array], scopes: [Array], acceptedScopes: [Array] } } }
```
