### ISSUE TITLE
Puppet emits error on reconnect

### ISSUE THREAD

**Issue by matejdro** [Sorunome/mx-puppet-slack#54]
If puppet disconnects, it appears to emit error on reconnecting:

```
Apr-27 01:39:19.654 [SlackClient:Client] debug: RTM event: goodbye
Apr-27 01:39:19.697 [SlackClient:Client] debug: RTM event: disconnected
Apr-27 01:39:19.698 [SlackClient:Client] info: RTM client got disconnected, reconnecting...
Apr-27 01:39:19.698 [SlackClient:Client] info: RTM client got disconnected, reconnecting...
Apr-27 01:39:34.702 [SlackClient:Client] error: Failed to re-start RTM client Error: Unhandled event 'start' in state 'connecting'.
    at StateMachine.handleUnhandledEvent (/opt/mx-puppet-slack/node_modules/finity/lib/core/StateMachine.js:76:13)
    at /opt/mx-puppet-slack/node_modules/finity/lib/core/HierarchicalStateMachine.js:79:33
    at TaskScheduler.execute (/opt/mx-puppet-slack/node_modules/finity/lib/core/TaskScheduler.js:29:7)
    at TaskScheduler.enqueue (/opt/mx-puppet-slack/node_modules/finity/lib/core/TaskScheduler.js:19:12)
    at HierarchicalStateMachine.handle (/opt/mx-puppet-slack/node_modules/finity/lib/core/HierarchicalStateMachine.js:72:24)
    at RTMClient.start (/opt/mx-puppet-slack/node_modules/@slack/rtm-api/dist/RTMClient.js:257:27)
    at Client.<anonymous> (/opt/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:170:35)
    at Generator.next (<anonymous>)
    at /opt/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:20:71
    at new Promise (<anonymous>)
Apr-27 01:39:34.999 [SlackClient:Client] debug: RTM event: authenticated
Apr-27 01:39:34.999 [SlackClient:Client] info: Reconnected!
Apr-27 01:39:35.270 [SlackClient:Client] debug: RTM event: ready
```

This is with version https://github.com/Sorunome/mx-puppet-slack/commit/95b4720fed1c12cc53a40a43f551081f123c394b

**Comment by Sorunome** [comment]
fixed in https://github.com/Sorunome/soru-slack-client/commit/3587540c35ef7780d375f04b95ce9ce87a0c6ec0
