### ISSUE TITLE
slack_webapi_platform_error limit_required

### ISSUE THREAD

**Issue by jsimonetti** [Sorunome/mx-puppet-slack#58]
When requesting the room list (using command 'listrooms') for the Gohpers slack I get an API error.
It looks like for this slack there is a need to page through the roomlist (it is big, approx 1,300 rooms)

```
matrix-slack             | Apr-29 09:42:23.139 [bot-sdk-Appservice] info: Processing transaction 12
matrix-slack             | Apr-29 09:42:23.140 [bot-sdk-Appservice] info: Processing event of type m.room.message
matrix-slack             | Apr-29 09:42:23.148 [BotProvisioner] info: Got message to process with arg=listrooms
matrix-slack             | 10.169.249.143 - - [29/Apr/2020:09:42:23 +0000] "PUT /transactions/12?access_token=xxx HTTP/1.1" 200 2 "-" "Synapse/1.12.4"
matrix-slack             | Apr-29 09:42:24.226 [MatrixEventHandler] error: Error handling appservice room.event Error: An API error occurred: limit_required
matrix-slack             |     at Object.platformErrorFromResult (/opt/mx-puppet-slack/node_modules/@slack/web-api/dist/errors.js:50:33)
matrix-slack             |     at WebClient.apiCall (/opt/mx-puppet-slack/node_modules/@slack/web-api/dist/WebClient.js:485:28)
matrix-slack             |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
matrix-slack             |   code: 'slack_webapi_platform_error',
matrix-slack             |   data: {
matrix-slack             |     ok: false,
matrix-slack             |     error: 'limit_required',
matrix-slack             |     response_metadata: { scopes: [Array], acceptedScopes: [Array] }
matrix-slack             |   }
matrix-slack             | }
```

**Comment by Sorunome** [comment]
Fixed in https://github.com/Sorunome/soru-slack-client/commit/445fcfa375124493ff91598634afe0938f790896
