### ISSUE TITLE
M->S messages are not reaching Slack private rooms

### ISSUE THREAD

**Issue by twouters** [Sorunome/mx-puppet-slack#59]
```
May 04 10:10:27 midgard node[505409]: (node:505409) UnhandledPromiseRejectionWarning: Error: An API error occurred: method_not_supported_for_channel_type
May 04 10:10:27 midgard node[505409]:     at Object.platformErrorFromResult (/home/twouters/mx-puppet-slack/node_modules/@slack/web-api/dist/errors.js:50:33)
May 04 10:10:27 midgard node[505409]:     at WebClient.apiCall (/home/twouters/mx-puppet-slack/node_modules/@slack/web-api/dist/WebClient.js:485:28)
May 04 10:10:27 midgard node[505409]:     at runMicrotasks (<anonymous>)
May 04 10:10:27 midgard node[505409]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
May 04 10:10:27 midgard node[505409]: (node:505409) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
```

**Comment by Sorunome** [comment]
> method_not_supported_for_channel_type

well......it claims sending messages wasn't supported ? o.O

**Comment by Sorunome** [comment]
with private rooms you mean `mpim`?

**Comment by Sorunome** [comment]
OOOOH sending a message now tries to join a room on first try, maybe `mpim` is always joined and thus doesn't support that. That should be an easy fix, if that is the case

**Comment by matejdro** [comment]
Same here. Logs with a bit more context:

```
May-4 09:07:14.595 [bot-sdk-Metrics] debug: matrix_client_function_call
May-4 09:07:14.600 [bot-sdk-Appservice] info: Processing transaction 11072
May-4 09:07:14.601 [bot-sdk-Appservice] info: Processing event of type m.room.message
May-4 09:07:14.601 [SlackPuppet:slack] info: Received create request for channel update puppetId=1 roomId=ROOM
May-4 09:07:14.602 [SlackPuppet:slack] info: Received create request for channel update puppetId=2 roomId=ROOM
May-4 09:07:14.602 [SlackPuppet:slack] info: Received create request for channel update puppetId=3 roomId=ROOM
May-4 09:07:14.602 [SlackPuppet:slack] info: Received create request for channel update puppetId=4 roomId=ROOM
May-4 09:07:14.602 [MatrixEventHandler] info: Got new message in !MY_ACC:my_server from @matejdro:my_server!
May-4 09:07:14.603 [MatrixEventHandler] info: Handling text event with msgtype m.text...
May-4 09:07:14.603 [MatrixEventHandler] debug: Emitting message event...
172.17.0.1 - - [04/May/2020:09:07:14 +0000] "PUT /transactions/11072?access_token=token HTTP/1.1" 200 2 "-" "Synapse/1.12.3"
May-4 09:07:14.610 [bot-sdk-MatrixLiteClient] debug: (REQ-989 RESP-H200) {}
May-4 09:07:14.610 [bot-sdk-Metrics] debug: matrix_client_function_call
(node:1) UnhandledPromiseRejectionWarning: Error: An API error occurred: method_not_supported_for_channel_type
    at Object.platformErrorFromResult (/opt/mx-puppet-slack/node_modules/@slack/web-api/dist/errors.js:50:33)
    at WebClient.apiCall (/opt/mx-puppet-slack/node_modules/@slack/web-api/dist/WebClient.js:485:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
```

**Comment by matejdro** [comment]
This happens when trying to send message to private channel.
