### ISSUE TITLE
Incoming message processing can fail with `Cannot read property 'ts' of undefined`

### ISSUE THREAD

**Issue by matejdro** [Sorunome/mx-puppet-slack#67]
I cannot reproduce this one, but when I used `/remind list` on actual slack client once and got response from the bot, puppet threw following error:

```
May-15 07:30:49.464 [SlackClient:Client] [34mdebug[39m: RTM event: message
May-15 07:30:49.464 [SlackClient:Client] [35msilly[39m: Processing message with data {
  type: 'message',
  subtype: 'message_changed',
  hidden: true,
  message: {
    type: 'message',
    subtype: 'bot_message',
    text: '[REDACTED]',
    is_ephemeral: true,
    user: 'USLACKBOT',
    username: 'slackbot',
    bot_id: 'BSLACKBOT',
    ts: '1589527846.010100'
  },
  channel: '[REDACTED]',
  ts: '1589527849.000000',
  event_ts: '1589527849.001900',
  team_id: '[REDACTED]'
}
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ts' of undefined
    at Message._patch (/opt/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/message.js:30:24)
    at new Message (/opt/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/message.js:27:14)
    at Client.<anonymous> (/opt/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:807:36)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:17:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Sorunome** [comment]
What is the expected behaviour? Just do nothing and don't delete anything?

Asking because soru isn't sure what slack reminders are and how they should work ^^

**Comment by matejdro** [comment]
You can test it out that way (all of this in the official slack client):

1. Enter `/remind me to do something in 3 hours` into any channel
2. Enter `/remind list` into any channel. You should get list of all your reminders
3. Select "Delete" next to your reminder on the list
4. List should update with your reminder now gone. However, this update never reaches the Matrix.
