### ISSUE TITLE
mpim messages do not reach Matrix

### ISSUE THREAD

**Issue by matejdro** [Sorunome/mx-puppet-slack#68]
1. Have someone create new MPM message with you and at least another person (this is how it reproduces for me, it might also happen for 1-on-1 messages).
2. Messages in this chat will not be received and bridge will error out:

```
May-15 10:23:58.278 [SlackClient:Client] [34mdebug[39m: RTM event: message
May-15 10:23:58.280 [SlackClient:Client] [35msilly[39m: Processing message with data {  
client_msg_id: '[REDACTED]',
  suppress_notification: false,
  type: 'message',
  text: '[REDACTED]',
  user: '[REDACTED]',
  team: '[REDACTED]',
  blocks: [ { type: 'rich_text', block_id: 'ffa', elements: [Array] } ],
  source_team: '[REDACTED]',
  user_team: 'T1Y6S5AHJ',
  channel: '[REDACTED]',
  event_ts: '1589538238.001000',
  ts: '1589538238.001000',
  team_id: '[REDACTED]'
}
(node:1) UnhandledPromiseRejectionWarning: Error: Channel not found
    at Client.<anonymous> (/opt/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:756:23)
    at Generator.next (<anonymous>)
    at /opt/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:16:12)
    at Client.getChannelAndAuthor (/opt/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:726:16)
    at Client.<anonymous> (/opt/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:804:52)
    at Generator.next (<anonymous>)
    at /opt/mx-puppet-slack/node_modules/soru-slack-client/lib/structures/client.js:20:71
    at new Promise (<anonymous>)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
```

This is with https://github.com/Sorunome/mx-puppet-slack/commit/45c5647dc5a0b342b4a754597790d0672d021701

**Comment by Sorunome** [comment]
is this fixed now? https://github.com/Sorunome/soru-slack-client/pull/8 might have fixed it

**Comment by matejdro** [comment]
This seems to work at first glance. Will reopen if I notice any issues. Thanks!
