### ISSUE TITLE
d cookie must be url-encoded

### ISSUE THREAD

**Issue by robintown** [Sorunome/mx-puppet-slack#82]
I am running `link xoxc-XXXXXXXXXXXX-XXXXXX… XXXXXXXXXX…` with my `xoxc` token and my `d` cookie from Slack, but I get the response "[Status] 2: Slack: Failed to connect client: Error: An API error occurred: invalid_auth".

The bridge logs show this:

```
Jul-16 00:55:44.015 [SlackClient:Client] error: Failed to start rtm client Error: An API error occurred: invalid_auth
    at Object.platformErrorFromResult (/home/slack-bridge/mx-puppet-slack/node_modules/@slack/web-api/dist/errors.js:50:33)
    at WebClient.apiCall (/home/slack-bridge/mx-puppet-slack/node_modules/@slack/web-api/dist/WebClient.js:485:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'slack_webapi_platform_error',
  data: { ok: false, error: 'invalid_auth', response_metadata: {} }
}
Jul-16 00:55:44.028 [SlackClient:Client] error: Failed to start rtm client Error: An API error occurred: invalid_auth
    at Object.platformErrorFromResult (/home/slack-bridge/mx-puppet-slack/node_modules/@slack/web-api/dist/errors.js:50:33)
    at WebClient.apiCall (/home/slack-bridge/mx-puppet-slack/node_modules/@slack/web-api/dist/WebClient.js:485:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'slack_webapi_platform_error',
  data: { ok: false, error: 'invalid_auth', response_metadata: {} }
}
Jul-16 00:55:44.032 [SlackPuppet:slack] warn: Failed to connect client Error: An API error occurred: invalid_auth
    at Object.platformErrorFromResult (/home/slack-bridge/mx-puppet-slack/node_modules/@slack/web-api/dist/errors.js:50:33)
    at WebClient.apiCall (/home/slack-bridge/mx-puppet-slack/node_modules/@slack/web-api/dist/WebClient.js:485:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'slack_webapi_platform_error',
  data: { ok: false, error: 'invalid_auth', response_metadata: {} }
}
```

I'm guessing this is a [Sorunome/soru-slack-client](https://github.com/Sorunome/soru-slack-client) bug?

**Comment by Sorunome** [comment]
try tossing your d cookie value through https://www.urlencoder.org/

Am 16. Juli 2020 07:09:43 MESZ schrieb Robin Townsend <notifications@github.com>:

**Comment by robintown** [comment]
Thanks, that did it! So I guess it ought to url-encode the cookie in the first place, wherever it actually goes into a HTTP request

**Comment by Sorunome** [comment]
fixed by now
